// Social artwork reuses the original podcast cover and the site's handwritten title.
import { createCanvas, loadImage, registerFont } from 'canvas';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const projectFile = (name) => fileURLToPath(new URL(`../${name}`, import.meta.url));
registerFont(projectFile('src/assets/fonts/Pacifico-Regular.ttf'), { family: 'PodcastPacifico' });
const canvas = createCanvas(1200, 630);
const ctx = canvas.getContext('2d');
ctx.fillStyle = '#fff9f1';
ctx.fillRect(0, 0, 1200, 630);
ctx.fillStyle = '#f4e9dc';
ctx.fillRect(0, 0, 500, 630);
const cover = await loadImage(projectFile('src/assets/images/podcast/show-cover.svg'));
ctx.save();
ctx.beginPath();
ctx.roundRect(55, 100, 390, 390, 20);
ctx.clip();
ctx.drawImage(cover, 55, 100, 390, 390);
ctx.restore();
ctx.font = '19px sans-serif';
ctx.fillStyle = '#64534b';
ctx.fillText('COFFEE. APPS. CURIOUS CONVERSATIONS.', 554, 139);
ctx.font = '58px PodcastPacifico';
ctx.fillStyle = '#ffb7a9';
ctx.fillText('Coffee & Fun', 556, 259);
ctx.fillText('Podcast', 556, 343);
ctx.fillStyle = '#914735';
ctx.fillText('Coffee & Fun', 554, 256);
ctx.fillText('Podcast', 554, 340);
ctx.fillStyle = '#64534b';
ctx.font = '23px sans-serif';
ctx.fillText('Every other week, on YouTube.', 554, 421);
ctx.font = '21px sans-serif';
ctx.fillText('First brew: October 31, 2026.', 554, 466);
ctx.font = '18px sans-serif';
ctx.fillText('coffeeandfun.com/podcast', 554, 551);
await writeFile(projectFile('src/assets/images/social/pages/podcast.png'), canvas.toBuffer('image/png'));
